# Base image
FROM node:14

# Create app directory
WORKDIR /usr/src/ui-app

# Install app dependencies
COPY package*.json ./
RUN npm install -g @angular/cli && npm install

# Bundle app source
COPY . .
RUN ng build --prod

# Expose port
EXPOSE 4100

# Command to run our app
# CMD [ "ng", "serve", "--host", "0.0.0.0", "--disable-host-check"]
CMD ["node", "server.js"]