# Base image
FROM node:14

# Create app directory
WORKDIR /usr/src/service-app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Expose port
EXPOSE 3000

# Command to run our app
CMD [ "npm", "start"]